### ISSUE TITLE
Filter Customers / Suppliers

### ISSUE THREAD

**Issue by bahron83** [scaphilo/koalixcrm#111]
I noticed that Customers and Suppliers don't have any filter_list available. The current class definition allows to add filters only for customer group and billing cycle attributes. It would be nice to filter customers (or suppliers) by many other attributes, such as town, or state, just to give two examples.
I understand the way of abstracting contact addresses (postal, email and phone) that was implemented, but it makes difficult to manage and analyze customer data.
Do you think adding new fields to the Contact class would be an option? Or you suggest another way to handle this?

**Comment by scaphilo** [comment]
Hello behron83 
Could you please provide some concrete example for your request?

Is it something like this:
On the customer list overview i would like to filter for all customers living in a specific city, street.
On the customers list overview I would like to search for a customer with a known phone address.
....
 or do you think about something else?

**Comment by bahron83** [comment]
Yes, you got the point. An example would be:
_On the customer list overview i would like to filter for all customers living in a specific city, street._

I am not a Django expert and after posting this issue I discovered how to implement custom filters using SimpleListFilter, so it's not complicated adding the kind of filters I'm proposing.
Do you think is would be the correct way to proceed?

I also think that having postal, email and phone addresses as independent classes let the user manage all this data with ease using inlines, but it would be nice to have a **Person** entity, because if you track activities such as marketing calls, meetings and so on, you'll probably want to link those activities to a specific person of reference, from the interested company (both Customer or Supplier).

**Comment by scaphilo** [comment]
The SimpleListFilter looks to be an exact fit to your requested improvement.
And its also supported from my side.

Regarding the requested new person entity - I think I understand your intention and I also support it in general.  

I saw that you have started to work on your fork  on both topics already.
Do you plan to prepare a pull request with the improvements soon?
This would be highly appreciated from my side! 
If you want me to review your changes before the pull request, let me know.

**Comment by bahron83** [comment]
Yes, I'd be glad to. I'll ask you to review the code as soon as it will be ready.

**Comment by scaphilo** [comment]
There seem to be an additional issue. The unnecessary differentiation between supplier and customer does not allow to send a delivery not to a supplier.

**Comment by scaphilo** [comment]
Hello bahron83, i see that you are working hard on your changes.
Could we try to merge the changes with the master soon? I just want to avoid that hacont, you and me are working too much in different directions. Also i would really like to support you in writing some unit test cases for you features

**Comment by bahron83** [comment]
Hi Scaphilo, I've been working on a bunch of features specific for a custom project and it took a while because I had little spare time for that.
I created a new branch (dev1) which contains only the changes we agreed on:

- new classes **Call** and **Visit** to manage commercial calls and on site work, such as meetings, installations, technical assistance
-new class **Person** to have a specific reference person to Calls and Visits
-new field **is_lead** to specify whether the Customer entry is an actual customer, or a potential customer
-State, Town and IsLead filter on Customers page, using SimpleListFilter

Speaking about the **is_lead** field: I think that we should be able to easily distinguish an actual Customer from a Lead, but we need to define the best option to show all the entries and the procedure to promote a Lead to a Customer (a simple boolean field maybe it's not strong enough).

I'll create a pull request if all above is fine with you.

**Comment by bahron83** [comment]
I see you developed a "Reporting" section containing Tasks and Works. My **Call** and **Visit** classes probably clash with Tasks, which would ideally be something more abstract.
The idea behind Call and Visit classes was about Leads management though; if you don't think that adding Call and Visit classes to your project is a good idea, I think you should consider how to use Tasks with Leads, particularly if you don't have any Contract to be used as ForeignKey in Tasks.

**Comment by scaphilo** [comment]
Thanks a lot for this preparation. From what you are writing it sounds good and I am very interested in integrating your branch soon. Because some of your changes will  likely lead to some issues with test cases i have written in the last three month i will create a branch where we can work together and try to fix all issues. Also I need to to find a good solution for the migration of the existing data.... 
I am looking forward for your pull-request

**Comment by scaphilo** [comment]
Regarding the Call and Visit clashing with the Tasks:
I was also experiencing some issues when the contract is hard linked with the tasks. I believe that all tasks will need to be linked through the GenericTaskLink.

I am not very sure what to do here:
On one hand: In all companies I know it is common that any tasks and any reported work is linked to a project  for controlling purpose. 
On the other hand: I do not believe that this is compatible with the lean and agile product development approaches

**Comment by bahron83** [comment]
I agree that a time consuming Task should be linked to a Project; this is for correctly managing budgets and controlling cost centres. In master branch, Tasks are currently linked to Contracts via ForeignKey though. In my opinion, there is a difference between a Contract and a Project, since a Contract implies an agreement with an actual Customer, while a Project is something more abstract. For example, Calls and Visits defined by classes listed above, could be seen as Tasks which should be linked to a Project which would be a _Customer acquisition project_. Since a Lead is not an actual Customer, no Contract can be linked to it, while a generic Project could.

**Comment by scaphilo** [comment]
Thanks a lot for you commits and the the implementation of calls and visits as well, good work!

Just two points we need to be careful in future
after reviewing your pull request i see that we have slightly different understanding of contact (you named it company in some parts of your code). Also person and people seems to be a synonym in your code.
I think we need to create a document that describes clearly what these classes represent in the real world otherwise we will have more and more confusion in future.

**Comment by bahron83** [comment]
Yes, I noticed this too and I agree with you.
What do you think about my comment above? Does it make sense to you having an abstract entity Project in the sense I described?

By the way, thanks for merging my pull request, I hope that will be of use!
