### ISSUE TITLE
Demo-Server need to be more robust and reliable

### ISSUE THREAD

**Issue by scaphilo** [scaphilo/koalixcrm#140]
The two demo instances of the koalixcrm do not really work reliable.
- User gets bad impression about the quality of the software
- Guest password reset.
- Time-consuming installation is very often not properly done 

The improved demo instance should work in a a docker container and should be set up with initial data so that guest user are not annoyed by set-up issues like: Missing tempaltesets, missing currency, wrong setting of the accounting period and so on.

**Comment by novski** [comment]
seams like the demo is offline.
