### ISSUE TITLE
Set up CI build with travis

### ISSUE THREAD

**Issue by Hacont** [scaphilo/koalixcrm#20]
As a developer I want to have a CI build which is executed right after each commit on GitHub to be sure, that the project can be built and all the tests are passing successfully.

**Comment by scaphilo** [comment]
could you run a "ls -al" command on the folder "/app" and on the folder "/app/sandbox" and post it here.
I have the feeling that we have some issues with the filesystem rights. You should see the following files:
db.sqlite3
manage.py
requirements.txt
(folder) static
(folder) test_koalixcrm

**Comment by Hacont** [comment]
Build and deployment on Heroku with Travis CI is configured and thested.
