### ISSUE TITLE
Customer billing cycle: POST request cause "Unsupported operand type" error

### ISSUE THREAD

**Issue by Hacont** [scaphilo/koalixcrm#208]
**Describe the bug**
Whenever the user tries to save a new customer billing cycle, the (POST request), an error page is displayed (see attachment)

**To Reproduce**
1. Go to the dashboard and click on "Customer bulling cycles" (Zahlungsbedingungen)
2. Click "Add customer billing cycle"
3. Fill in the form (Name: Test, Days To Payment Date: 30, Payment Reminder Days... : 5)
4. Click one of the save buttons
5. See the error page

**Expected behavior**
I expect, that the new billing cycle is created, the creation page is closed and the list of existing billing cycles (table view) is opened and includes the newly created billing cycle object.

**Screenshots**
![image](https://user-images.githubusercontent.com/1700194/46598936-324d0f80-cae6-11e8-97ef-4f3145e89a8f.png)

**Comment by scaphilo** [comment]
Thanks a lot for the good issue report!!
An other user reported the same issue. The issue seems to be fixed within the pull request #210.
However i will keep this issue here to remind me to create a selenium testcase for each admin view

**Comment by scaphilo** [comment]
#222 created
