### ISSUE TITLE
Time Tracking Module

### ISSUE THREAD

**Issue by looneyapache** [scaphilo/koalixcrm#244]
**Describe the bug**
When I am in Time tracking mode - by default a new "row" is added.
Now if add a "row" and delete previous row - I get Server error 500.

**Expected behavior**
I expected Previous "row"/"record" to be deleted apparently I have not "committed/saved"

I am Fedora 28/Firefox 64.0 (64 bit) and Chrome 3.23.17

![image](https://user-images.githubusercontent.com/10562851/50574503-e9200980-0e0f-11e9-900e-98d27f8501f1.png)
![image](https://user-images.githubusercontent.com/10562851/50574510-110f6d00-0e10-11e9-9fb3-6c0862bcf8cf.png)

**Comment by scaphilo** [comment]
Thank you for reporting the issue, i will try to reproduce it asap

**Comment by scaphilo** [comment]
I was able to reproduce the issue - Bugfix is in work

**Comment by looneyapache** [comment]
Thank you,Mate!!! :)
