### ISSUE TITLE
What is the correct support channel

### ISSUE THREAD

**Issue by goetzk** [scaphilo/koalixcrm#32]
Hi,
I've built up a big list of questions/comments while reviewing koalixcrm and wondered what the proper way of discussing them is. GH and the docs don't mention support at all.

**Comment by scaphilo** [comment]
Hello
So I think for the moment we should stay with the github issues to discuss questions and comments. When the community grows and the issues system would not be sufficient anymore we could go for something like the google group https://groups.google.com/forum/#!forum/koalixcrm-users

I just added a new possible label for the Issues "question" which can be used for such topics

are you also OK with that proposal or would you recommend something else?

**Comment by goetzk** [comment]
Sounds perfectly reasonable to me. I'll post a few more questions to GH soon, pending me time to do my own checking of them before I do so.
