### ISSUE TITLE
Refactor project structure

### ISSUE THREAD

**Issue by Hacont** [scaphilo/koalixcrm#42]
As a developer I would like to refactor the project structure to have a better overview over the different components of the project. It will statisfy the requirements for multi-target environment configuration.

# My proposal for the new project structure:
- koalixcrm
    - apps
        - accounting
            - const
            - locale
            - management
            - migrations
            - tests
        - crm
            -  ....
        - djangoUserExternsion
            - .... 
       - substriptions
            - ...
        - static
        - templates
    - documentation
    - koalixcrm
        - settings
            - _environment1_settings.py_
            - _environment2_settings.py_
            - ...
        - _globalSuppoertFunctions.py_
        - _plugin.py_
        - _urls.py_
        - _wsgi.py_
    - requirements
    - _CODE_OF_CONDUCT.md_
    - _CONTRIBUTING.md_
    - _LICENCE_
    - _manage.py_
    - _MANIFEST.in_
    - _Procfile (required by Heroku)_
    - _README.md_
    - _requirements.txt (required by Heroku)_
    - _setup.py_

**Comment by scaphilo** [comment]
Sounds good, I agree with the proposed structure.
