### ISSUE TITLE
Pinned django dependency via pypi

### ISSUE THREAD

**Issue by derek-adair** [scaphilo/koalixcrm#43]
I use a mish-mash of various open source apps that have a fairly wide variety of django version requirements.

Currently I am trying to plug koalix to be a django-CMS addon via to the [Divio](http://divio.com) platform.  There are two packages that require <1.11 and I would like to keep using their versions. 

**Is django 1.11.4** *really* **a hard dependency?**  Not even ~=1.11?  Does it break in < 1.11?

**Comment by derek-adair** [comment]
Also i reduced the deps to Django>=1.9.x and it SEEMS to work just fine, i need to find the tests and run them still but i've been playing around with the tutorial and stuff... seems to work.

**Comment by scaphilo** [comment]
As we are currently working on the tests  and the coverage and we did not progress very far right now.
This is why it would be quite timeconsuming to give you a reliable answer.

**Comment by scaphilo** [comment]
But i have good feeling until 1.10 because i did most changes within this release with this version.

**Comment by derek-adair** [comment]
Very cool.  I'll be watching.

**Comment by scaphilo** [comment]
I just adjusted the requirements to also allow django 1.9.x 
Still we need some tests to make sure this actually works as well.

**Comment by derek-adair** [comment]
Cheers!
