### ISSUE TITLE
Swiss Account Tables?

### ISSUE THREAD

**Issue by derek-adair** [scaphilo/koalixcrm#44]
This [mention](https://koalixcrm.readthedocs.io/en/master/tutorial.html#create-accounts) of swiss accounts is confusing.  This leads me to believe this is not compatible with american accounts in some way?

Could you please clarify.

**Comment by scaphilo** [comment]
I will improve the text and put a picture there.

What i tried to state in this section is that the naming and numbering of the accounts follow some rules.
Example from switzerland:
All assets have numbers between 1000-1999 (where the most liquid assets have the lowest number)
All liabilities have numbers between 2000-2999 (where the most shortterm liabilities have lowest numbers)
At the moment I dont know whether this is an international standard or just a swiss standard.

If someone knows more about these rules it would be very helpful. Please post links here.

**Comment by derek-adair** [comment]
Ok, that makes sense.  I'm really not familiar with billing / accounting in general and I was just curious.
