### ISSUE TITLE
Project should exist independent from contracts

### ISSUE THREAD

**Issue by scaphilo** [scaphilo/koalixcrm#71]
**Context:**
Projects are used for budgeting reasons. Employees can report work on the projects.
Projects may exists independent from contract with customers
Projects may be used to acquire new customers and and new contracts.
Sometimes a project can be linked to different contracts

Contracts are agreements between a customer and the company.
Contracts may result in a project
Sometimes it is required to have several projects within a contract

**Current situation**
There is no differentiation between Contract and Project, there exists only the Contract entity in the database

**Required situation**
There exists two different entitities in the database.
The project will be in the software package "reporting" (sub package of crm)
The contract will stay where it was software package "document" (sub package of crm)
Through an admin-action it possible to create a project from a contract
Through an admin-action it is possible to create a contract from a project

Questions:
Do we need departments where the costs for internal projects will be acquired
When we have a department model - would it require an action "create a project"

**Comment by scaphilo** [comment]
@bahron83 and @Hacont could you please share your opinion to above statements

**Comment by bahron83** [comment]
Hi @scaphilo, to answer your questions:

> Do we need departments where the costs for internal projects will be acquired
I think that costs for every project should be assigned to a specific department, not only the internal ones. And when I speak about costs, I think about both financial (eg. purchases) and working hours. 

> When we have a department model - would it require an action "create a project"
A project may involve one or more departments, hence I don't think that creating a project from within a department is particularly useful.

By the way, I haven't examined your last commits yet and maybe I didn't correctly understand the questions, so tell me if you agree with my points.
