### ISSUE TITLE
Demo 

### ISSUE THREAD

**Issue by sottany** [scaphilo/koalixcrm#9]
The Guest id and password for you website ate not working i need a demo of you website give me its guest login

**Comment by kakohari** [comment]
May I kindly request a reset of the demo-login, too, once again :)

**Comment by scaphilo** [comment]
Thx for the input, wrong password is fixed again.

**Comment by artforlife** [comment]
I believe this is not working, again.

**Comment by henan715** [comment]
in 2017-06-12 , the password of guest was wrong, please fix it again~

**Comment by scaphilo** [comment]
Thx for the input, wrong password is fixed again.
