### ISSUE TITLE
koalixcrm.org demo is down

### ISSUE THREAD

**Issue by salian** [scaphilo/koalixcrm#95]
http://www.koalix.org/ is inaccessible when viewed from the Chrome web-browser, with the message "ERR_CONNECTION_REFUSED".

**Comment by scaphilo** [comment]
hello salian
Yes sorry this is a known issue. I was shutting down the server but we will soon publish a new demo based on heroku

**Comment by h-2-0** [comment]
@scaphilo,  can't wait to check that demo out! Thanks! :)

**Comment by scaphilo** [comment]
fixed :-)

**Comment by h-2-0** [comment]
@scaphilo,

Thanks so much! I'll check it out tomorrow (it's very late here :)

**Comment by datatalking** [comment]
Where is the link @scaphilo ?

**Comment by scaphilo** [comment]
Hallo, thank you for the input
I am sorry, the demo will be up again in a few days. I am currently working on an automated deployment process to ensure these kind of issues do not appear anymore
